resolver: lts-19.30
packages:
- .

extra-deps:
- git: https://github.com/Javran/kantour.git
  commit: 0f3543224234d5e3f45b8424ff45856c49b21bed
  subdirs:
    - kantour-core
- aeson-2.0.3.0
- git: https://github.com/Javran/aeson-picker.git
  commit: c5b898e11fb50aeabc1a6fc2ab3ffbfc716a3b15
