resolver: lts-19.30
packages:
- .

extra-deps:
- git: https://github.com/Javran/kantour.git
  commit: e3ad862bc12501a0575589b136072173a701b147
  subdirs:
    - kantour-core
- aeson-2.0.3.0
- git: https://github.com/Javran/aeson-picker.git
  commit: c5b898e11fb50aeabc1a6fc2ab3ffbfc716a3b15
